### PR TITLE
chore: update default path to /docs/latest/

### PR DESCRIPTION
**Pull request by molant**
Adjust scripts to take into account the new path for the documentation
so we can be future proof if we ever decide to have versioning.

### CODE REVIEW

**Comment by molant** [comment]
I'm sure there's a prettier way to do this but we can probably postpone this for when we do versioning.

**Review by erickzhao — COMMENTED** [review]
Seems like there's a deploy failure

**Comment by molant** [comment]
@erickzhao deployment is finally green!

**Comment by molant** [comment]
This is obsolete after #42 got merged 🎉

**Pull request closed without merging**
