### PR TITLE
feat: Twerk crowdin.yml

### PR DESCRIPTION
**Pull request by Biki-das**
twerked the crowdin.yml with appropriate changes

### CODE REVIEW

**Comment by molant** [comment]
Thanks for you PR @Biki-das!
Can you please explain what you mean by "appropriate changes"?

**Comment by Biki-das** [comment]
> Thanks for you PR @Biki-das! Can you please explain what you mean by "appropriate changes"?

by appropriate i meant the typical format of crowdin.yml .

**Comment by Biki-das** [comment]
@molant  why my pr is semantically incorrect? not able to figure out

**Comment by molant** [comment]
The title needs to be something like `fix: this` `feature: another thing` `chore: bla`

The Crowdin file is working as we are using the defaults and it validates so I'm not sure this change is necessary.
@erickzhao what do you think?

**Comment by Biki-das** [comment]
> The title needs to be something like `fix: this` `feature: another thing` `chore: bla`
> 
> The Crowdin file is working as we are using the defaults and it validates so I'm not sure this change is necessary. @erickzhao what do you think?

ok , the crowdin have this as their configuration file - https://support.crowdin.com/configuration-file/#writing-a-simple-configuration-file,  this might help.

**Pull request closed without merging**
